# Generated by Django 6.0.1 on 2026-02-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Paid'), ('REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACCOUNT_UPDATED', 'Account Updated'), ('APP_MAINTENANCE', 'App Maintenance'), ('LOCKED', 'LOCKED'), ('BANNED', 'BANNED'), ('FROZEN', 'FROZEN'), ('LOAN_PAID', 'Loan Paid'), ('WITHDRAWAL_SUCCESSFUL', 'Withdrawal Successful'), ('INVALID_DETAIL', 'Invalid Detail'), ('LOW_CREDIT', 'Low Credit'), ('RENEW_DOCUMENT_REQUIRED', 'Renew Document Required'), ('RENEW_OTP_CODE', 'Renew OTP Code'), ('RENEW_DOCUMENT_AND_OTP', 'Renew Document & OTP code'), ('OVERDUE_RECORD', 'Overdue Record'), ('REPAYMENT_ABILITY', 'Repayment Ability'), ('VIP_CHANNEL', 'VIP Channel'), ('PURCHASE_LIFE_INSURANCE', 'Purchase Life Insurance'), ('TAX_VERIFICATION', 'Tax Verification'), ('PLATFORM_FEE', 'Platform Fee'), ('AMLC_WARNING', 'AMLC Warning')], default='ACTIVE', max_length=50),
        ),
    ]
