# Generated by Django 6.0.1 on 2026-02-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='progress_step',
            field=models.CharField(choices=[('LOAN_FORM', 'Step 1: Loan Form'), ('PAYMENT_METHOD', 'Step 2: Payment Method'), ('SUBMITTED', 'Step 3: Submitted')], db_index=True, default='LOAN_FORM', max_length=30),
        ),
    ]
