# Generated by Django 6.0.1 on 2026-02-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_loanapplication_progress_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate_monthly',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_repayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
