# Generated by Django 6.0.1 on 2026-02-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_loanapplication_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='withdrawal_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
