# Generated by Django 6.0.1 on 2026-02-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_loanapplication_withdrawal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='withdrawal_code',
        ),
    ]
