# Generated by Django 6.0.1 on 2026-02-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='credited_to_balance',
            field=models.BooleanField(default=False),
        ),
    ]
