# Generated by Django 6.0.1 on 2026-03-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_loanapplication_credited_to_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_control',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
