# Generated by Django 6.0.1 on 2026-03-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_user_is_control_user_is_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_status_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
