# Generated by Django 6.0.1 on 2026-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_withdrawalrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
