# Generated by Django 6.0.1 on 2026-07-10 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_restore_render_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', max_length=120)),
                ('target_label', models.CharField(blank=True, default='', max_length=160)),
                ('action', models.CharField(choices=[('STATUS', 'Status change'), ('BALANCE', 'Balance change'), ('NOTIFICATION', 'Notification message'), ('SUCCESS_MSG', 'Success message'), ('DELETE', 'Client deleted')], db_index=True, max_length=20)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchdog_actions', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchdog_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
