# Generated by Django 6.0.1 on 2026-07-11 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_staffaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=120)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('device_label', models.CharField(blank=True, default='', max_length=200)),
                ('device_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_new_device', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff login device',
                'verbose_name_plural': 'Staff login devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
