# Generated by Django 6.0.1 on 2026-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_staffloginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='device_lock_enabled',
            field=models.BooleanField(default=False, help_text='When ON, each staff can only log in from one approved device; a new device is blocked until you Allow it.'),
        ),
        migrations.AddField(
            model_name='user',
            name='allowed_device',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_device',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_device_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_device_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
