# ============================================================
# OFL - Sync backups from the private backup repo to local
# ============================================================
# Daily backups are generated by GitHub Actions in the private
# repo  vainglory0601-arch/mana_system2_backup  (runs at 02:00
# Asia/Manila on GitHub's servers - PC being off is fine).
# Each dump is committed there as
#     backups/backup-YYYY-MM-DD_HHmm.json
#
# This script clones / pulls that repo into a hidden cache
# folder, then copies every new JSON file into
#     c:\Mana_system2\backups\
# so you have a local mirror of every day's dump.
#
# First run: prompts to clone the repo (needs a GitHub PAT or
# SSH key that can read mana_system2_backup).
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\sync_backups.ps1
# ============================================================

$ErrorActionPreference = "Stop"

$ProjectRoot   = "C:\Mana_system2"
$LocalBackups  = Join-Path $ProjectRoot "backups"
$CacheRoot     = Join-Path $env:LOCALAPPDATA "OFL-Backup-Cache"
$RepoUrl       = "https://github.com/vainglory0601-arch/mana_system2_backup.git"

if (-not (Test-Path $LocalBackups)) {
    New-Item -ItemType Directory -Path $LocalBackups | Out-Null
}
if (-not (Test-Path $CacheRoot)) {
    New-Item -ItemType Directory -Path $CacheRoot | Out-Null
}

$RepoCache = Join-Path $CacheRoot "mana_system2_backup"

# --- Clone on first run, pull thereafter ---
if (-not (Test-Path (Join-Path $RepoCache ".git"))) {
    Write-Host "[sync_backups] First-time clone -> $RepoCache"
    git clone --depth 50 $RepoUrl $RepoCache
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Clone failed. Make sure you can read $RepoUrl in a browser. If the repo is private, set up a PAT/SSH key for git."
        exit 1
    }
} else {
    Write-Host "[sync_backups] Pulling latest backups..."
    Push-Location $RepoCache
    try {
        git fetch origin main --depth 50 2>&1 | Out-Null
        git reset --hard origin/main 2>&1 | Out-Null
    } finally { Pop-Location }
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Pull failed. Check your network or git credentials."
        exit 1
    }
}

# --- Copy any new dump into the local backups/ folder ---
$RemoteBackups = Join-Path $RepoCache "backups"
if (-not (Test-Path $RemoteBackups)) {
    Write-Warning "Backup repo has no  backups/  folder yet. Has the workflow run at least once?"
    exit 0
}

$copied = 0
Get-ChildItem -Path $RemoteBackups -Filter "backup-*.json" | ForEach-Object {
    $dest = Join-Path $LocalBackups $_.Name
    if (-not (Test-Path $dest)) {
        Copy-Item $_.FullName $dest
        Write-Host "[sync_backups]   + $($_.Name)"
        $copied++
    }
}
Write-Host "[sync_backups] $copied new file(s) copied to $LocalBackups"
Write-Host "[sync_backups] Done."
